spring.application.name=NotesApp

spring.datasource.url=jdbc:postgresql://dpg-d741rv5m5p6s73f0kqk0-a:5432/notes_db_f8ew
spring.datasource.username=notes_db_f8ew_user
spring.datasource.password=9a7nBIbMHtD7UcafAFkNJMlrSNQFgsFZ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional
spring.jpa.open-in-view=false
