spring.application.name=NotesApp

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/notesdb
spring.datasource.username=root
spring.datasource.password=Aman@9340

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional (removes warning)
spring.jpa.open-in-view=false