spring.application.name=NotesApp

# Database (auto-read from environment)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Recommended
spring.jpa.open-in-view=false

# Debug (optional - remove later)
spring.jpa.show-sql=true
logging.level.org.springframework=DEBUG
